language: c
sudo: required
dist: trusty
compiler: gcc
before_install:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository ppa:gnome3-team/gnome3 -y
  - sudo add-apt-repository ppa:gnome3-team/gnome3-staging -y
  - sudo apt-get update
  - sudo apt-get install libglib2.0-dev libcmocka-dev libcmocka0
script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_STUDIO=OFF -DCOVERALLS=ON ..
  - make
after_success:
  - make coveralls


